# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Andrew-Kulpa/action-release
description: 'Github Action for uploading Github Releases Assets'
author: Andrew Kulpa
inputs:
  # file uploading
  files:
    description: 'Files to upload to the release'
    default: ''
  file:
    description: 'File to upload to the release'
    default: ''
  # release message body
  bodyFile:
    description: 'Path to text file for the body of the release'
    default: ''
  body:
    description: 'Body of the release'
    default: ''
  # file compression
  archiveType:
    description: 'Type of compression ("zip", "gz", or no compression) defaults to no compression'
    default: ''
  output:
    description: 'The name of an output archive file'
    default: ''
  # Tag naming and id
  tag:
    description: 'The tag identifier for the release'
    default: ''
  name:
    description: 'The name for the release'
    default: ''
  # release settings
  overwrite:
    description: 'Delete and re-release with matching tag'
    default: false
  prerelease:
    description: 'Set the release as a prerelease'
    default: false
  draft:
    description: 'Set the release as a draft'
    default: false
  token:
    description: 'Github Auth Token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'lib/main/main.js'
branding:
  color: 'green'
  icon: 'package'
