name: action-release Smoke Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - 'release/*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix: 
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build the project
        run: npm run build
      - name: Test the source files
        run: npm run test
